### ISSUE TITLE
Enhanced UUID package

### ISSUE THREAD

**Issue by truongsinh** [fluttercommunity/community#12]
I would like to include this package to Flutter Community https://pub.dartlang.org/packages/uuid_enhanced#-changelog-tab-

Changelog from since being forked:
- Strong mode on `dartanalyze`.
- Github pipeline (code coverage is on TODO).
- Use `Uint8List` instead of `List<int>` for performance (space and time).
- All constructor options are now named arguments instead of a map.
- `Uuid` is a type now (subtype of `Uint8List`) instead of a string, with proper implementation of `==` and `hashCode`.
- No more singleton, all creating methods are now constructor.
- `v1` renamed to `fromTime`, `v4` renamed to `emptyUuid`, `v5` renamed to `fromName`, `parse` renamed to `fromString`, `unparse` changed to instance method `toString`.
- New APIs `isFromTime`, `millisecondsSinceEpoch`, `clockSequence`.

**Comment by jeroen-meijer** [comment]
Hi there.

I've checked out the package.
Are you asking for it to be included in the Flutter Community?

**Comment by truongsinh** [comment]
Thanks, I added the description, it's correct that I'm asking the package to be included to Flutter Community.

**Comment by jeroen-meijer** [comment]
Sure!
We'll have a look at it and do a quick code review :)
We'll contact you shortly.

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for waiting. I recommend you contact the owner of the original UUID package (@ https://pub.dev/packages/uuid) to see if you can merge your changes with his package for better compatibility.
If this fails, we'll see what we can do.
We would rather have one great package on pub.dev rather than a popular one and a better alternative.

Please let us know how this goes.
Good luck.

**Comment by jeroen-meijer** [comment]
Any updates on this?

**Comment by jeroen-meijer** [comment]
Closing due to lack of reply. Feel free to comment and it can be reopened.
