### ISSUE TITLE
Package Proposal: states_rebuilder

### ISSUE THREAD

**Issue by GIfatahTH** [fluttercommunity/community#18]
# Package Proposal: states_rebuilder

**Dependency name (as used in *pubspec.yaml*):** states_rebuilder
**Current pub.dev Link:** https://pub.dev/packages/states_rebuilder
**Description:** a simple yet powerful state management and dependency injection techniques for Flutter
**Current maintainer:** meltft@gmail.com, GIfatahTH
**Needs new maintainer after transfer:** NO
**Reason for transfer:** Make the community aware of the package

**Comment by GIfatahTH** [comment]
Closed. More than one month whith no feedback.

**Comment by jeroen-meijer** [comment]
Hello there,

I’m sorry for the lack of feedback. The community staff has been quite busy recently.

As for the package, we’re currently discussing what the best course of action is, since this package has to do with state management, and the landscape for state management packages is quite big at the moment. We want to make the right decision, and we need some time for that.

We’ll get to a conclusion soon.
I’ll message you as soon as we do.

Best regards.

**Comment by jeroen-meijer** [comment]
Hi there,

I wanted to give an update regarding this package.

At this time, we don't yet want to get involved with full-on state management packages and put them in the Flutter Community.
I believe this might create the impression to users that one state management method is 'better' than another, while this is not the case. There are a lot of options out there, and all of them, including this one, have their strengths and weaknesses. As @brianegan put it well, "use the right tool for the job".

I hope this helps clear up why your package isn't included in the Flutter Community organisation.
My stance on this may change in the future, though, so keep a look-out for changes to our guidelines.

Thanks for your understanding.

Best regards.

_Disclaimer: all opinions above are my own and do not represent the ones from the entire Flutter Community Team._
