### ISSUE TITLE
Package Proposal: bottom_nav

### ISSUE THREAD

**Issue by viztushar** [fluttercommunity/community#25]
# Package Proposal: bottom_nav

**Dependency name (as used in *pubspec.yaml*):** bottom_nav
**Current pub.dev Link:** https://pub.dev/packages/bottom_nav
**Description:** A bottom navigation bar with expanding titles and icons with Rounded Background. Inspired by the Dribbble design here: https://t.co/BtUlszSmRR
**Current maintainer:** Tushar Parmar. viztushar@gmail.com, github:- viztushar
**Needs new maintainer after transfer:** NO
**New maintainer (if applicable):** -
**Reason for transfer:** so that flutter community can use it and make it more easy to use and add more custom UI Widget in the package.(and also Want to give back!)
**Comments:**

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for submitting your package, and sorry for the long wait.

Even though I feel that this is a nice package to have, especially because it speeds up UI building, I don't think it fits the Flutter Community. There are a lot of nav bar packages out there, and it feels wrong to host one on the Flutter Community because that might give the idea that it's better than other nav bars, which is not the case -- it's a case of preference and taste.

That said, I do have some tips for you if you'd like to improve your package.

---

1. **Documentation.**
The documentation is either missing, improperly formatted (using `//` instead of `///`) or contains slightly incorrect spelling or grammar (such as missing periods). Please ensure all classes and fields have proper documentation. (Check the [Dart doc guide](https://dart.dev/guides/language/effective-dart/documentation) for reference.)
To see which parts are missing, try adding `analysis_options.yaml` file to the root of the project (next to `lib`, `pubspec.yaml`, etc.) and put this in it:
```yaml
linter:
  rules:
    - public_member_api_docs
    - package_api_docs
    - slash_for_doc_comments
```
2. **Bottom padding not accounted for.**
When running on an iPhone X or other phone with special padding, the nav bar clips.
Consider adding a [`SafeArea`](https://api.flutter.dev/flutter/widgets/SafeArea-class.html) or using [`MediaQuery.of(context).padding`](https://api.flutter.dev/flutter/widgets/MediaQueryData/padding.html).
![image](https://user-images.githubusercontent.com/14292245/72329745-954c2f80-36b5-11ea-9195-fae2e2d83d49.png)

---

Thanks again for your submission.
Good luck with your package!

Closing.
