### ISSUE TITLE
Package Proposal: redux.dart

### ISSUE THREAD

**Issue by brianegan** [fluttercommunity/community#27]
# Package Proposal: Redux.dart

**Dependency name (as used in *pubspec.yaml*):** redux
**Current pub.dev Link:** https://pub.dev/packages/redux
**Description:** Redux is a predictable state container for Dart and Flutter apps
**Current maintainer:** Brian Egan (@brianegan / brian@brianegan.com) and John Ryan (@johnpryan)
**Needs new maintainer after transfer:** NO
**Reason for transfer:** Redux is a fairly popular package that currently lives under John's personal GitHub. Since the package is the work of the community -- with code, issues, help and documentation provided by many members of the community, we'd like to recognize the package as a work of the community.

**Comment by brianegan** [comment]
ping @johnpryan

**Comment by johnpryan** [comment]
Commenting to keep this open: I think we just need confirmation from @jeroen-meijer that this package will be accepted and that @brianegan and I can remain maintainers.

**Comment by jeroen-meijer** [comment]
Yep, I haven't been able to do that much community work as I'd like to. Will get to this soon (hopefully).
Sorry for the long waiting.

**Comment by johnpryan** [comment]
no problem!

**Comment by jeroen-meijer** [comment]
# Approved

Hi guys.

Thanks for submitting this packages.
It has been reviewed and approved for release on the Flutter Community GitHub. 🎉
Great work.

## What to do next
Please follow **steps 3 through 7** in the [Flutter Community Transfer Guide](https://github.com/fluttercommunity/transfer-guide#3-update-pubspecyaml).

Good luck.

**Comment by johnpryan** [comment]
@brianegan @jeroen-meijer I don't have access to publish to pub anymore. Could I be added as an uploader?

**Comment by jeroen-meijer** [comment]
Due to a miscommunication, I'm currently not an uploader of fluttercommunity.dev packages. @brianegan seems like you'll have to do it.

**Comment by jeroen-meijer** [comment]
Hi there 👋🏻

Are there updates on this?

**Comment by brianegan** [comment]
@johnpryan I saw you'd been making changes to the repo to get it ready to move over. It looks like most of the steps had been taken care of, but maybe we just need to publish the changes and migrate the Github repo at this point?

**Comment by johnpryan** [comment]
SGTM - I don't think I can't publish this package to Pub anymore though.

**Comment by johnpryan** [comment]
I'm also not able to transfer this repo here... do I need to be added to this organization first?

**Comment by jeroen-meijer** [comment]
Sorry, that's a fault on my end.
Since the pub.dev publishing architecture has recently changed, our workflow needs to be updated accordingly.

Here are the final steps.

# Transfer ownership on pub.dev
You've just been added as a Flutter Community pub.dev publisher member. Please check your email (`john.p.ryan4@gmail.com`). If this is not the right email, let me know.

Accept the invite, then go to your package and transfer ownership to `fluttercommunity.dev`
<img width="760" alt="image" src="https://user-images.githubusercontent.com/14292245/80212853-8cfe7b80-8638-11ea-8c29-cf6eaa3d6a3b.png">

# Transfer the package to the organization

You have also been invited to be a member of the Flutter Community GitHub organization. After accepting your invitation, please go to your repository's settings and transfer the package to the user/organization `fluttercommunity`.
<img width="767" alt="image" src="https://user-images.githubusercontent.com/14292245/80213099-f54d5d00-8638-11ea-8fd4-f939a9b55384.png">


Let me know if you have any questions or need help! 👍🏻

**Comment by johnpryan** [comment]
Transferred - thanks!

**Comment by jeroen-meijer** [comment]
Awesome, thank you guys for the cooperation! 👍🏻
