### ISSUE TITLE
Package Proposal: list_tile_more_customizable

### ISSUE THREAD

**Issue by Playhi** [fluttercommunity/community#45]
# Package Proposal: list_tile_more_customizable

**Dependency name (as used in *pubspec.yaml*):** list_tile_more_customizable
**Current pub.dev link:** https://pub.dev/packages/list_tile_more_customizable
**Current Git repository link:** https://github.com/Playhi/list_tile_more_customizable
**Description:** A ListTile with more customizable details, which provides more customizable functions, based on the traditional flutter ListTile.
**Current maintainer:** Playhi ( @Playhi / 000902play@gmail.com )
**Needs new maintainer after transfer:** NO
**Reason for transfer:** I have no more idea on the aim of the package now. If someone has some ideas on making the list_tile_more_customizable much more customizable, it is easier to add the ideas to the package if this package had been transferred.

**Comment by Playhi** [comment]
Closing due to 3 days+ no response. Feel free to comment and it can be reopened.

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for the package proposal.
Due to recent events within the community and the world overall, we're currently quite busy and will not be able to respond to most package proposals and other community inquiries on GitHub as well as you might expect. Sorry about that. We'll keep you up to date.

Thank you for understanding.

Best regards,
Jay (Flutter Community GitHub admin).
