### ISSUE TITLE
Forking an abandoned project

### ISSUE THREAD

**Issue by Leptopoda** [fluttercommunity/community#71]
# Discussion: [Fork for responsive_scaffold]

Hi there, 
I started using [responsive_scaffold](https://github.com/fluttercommunity/responsive_scaffold) and enjoy using it. sadly the development has stagnated so I started my own fork adding functionality I needed. I would be happy if I can contribute those back but the project seems to be abandoned (no interaction in the issues, no PR's closed and no commits for the last year).
I've already migrated the package to null saftey and opened a PR for that but I don't see my efforts helping any time soon.

Is it possible to ask for a maintainer change? I'd be happy to help develop this package further :)
So @rodydavis what about that?

## Summary
[Tell us about the topic and why you'd like to start a discussion.]

**Comment by jeroen-meijer** [comment]
Hi there,

Thanks for bringing this to my attention! I'll tell the team and we can get a new maintainer (perhaps you 👀) on this if needed. You'll hear from us. In the meantime, I suggest you keep using your fork.

But we do really want new changes to be merged with this repo, rather than having 100 forks. That's the whole reason the community repositories exist in the first place 😄 👍🏻 

cc @mhadaily @slightfoot @rodydavid

**Comment by rodydavis** [comment]
Please feel free to make a PR and I can merge, I have been going through all my packages in alphabetical order and migrating then to null safety. 

Publicly there haven’t been commits but I keep them updated since I use them In my apps. I don’t mind having another top level contributor but there are some things that need to be considered for package direction.

I also agree about not having various forks, but also the flexibility of flutter being able to fork a package a customize it to your needs.

**Comment by Leptopoda** [comment]
Thanks for the info @rodydavis 
A PR for null safety is already in place so just have a look when you have time.

> I don’t mind having another top level contributor but there are some things that need to be considered for package direction.

Yeah of course I was just curious if this project was dead.

> I also agree about not having various forks, but also the flexibility of flutter being able to fork a package a customize it to your needs.

I agree that not everything is needed upstream but as said above null safety was a big thing so I shared it. I’ll probably stay with my (private) fork anyways and just share where aplicable. 

If this was all I guess we can close this one 🙃

**Comment by rodydavis** [comment]
Ok wonderful! And perfect 😁
